---
title: "Project 1"
author: "Jeannie Hong"
date: "10/17/2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

### 0) Introduction

The two datasets that I have chosen for this project is the Global Suicide Data (MH_12) and World Happiness Report (X2015), which were both found on kaggle.com. The Global Suicide Data contains 6 variables (Country, Sex, 2015, 2010, 2005, 2000) and 549 observations. It gives you the age-adjusted suicide rate (per 100,000) in different countries based on year and sex. The World Happiness Report contains 12 variables (Country, Region, Happiness rank, Happiness score, Standard Error, Economy, Family, Health, Freedom, Trust, Generosity, Dystopia residual) and 158 observations. It gives you the happiness score of various countries and divides the score into different components that contribute to the happiness score. I thought these two datasets were interesting to look at since suicide and mental health is a issue of growing concern, and I wanted to examine how happiness plays a role in suicide rates. Suicide is becoming more and more common, and understanding factors that influence its rate can help us prevent unecessary deaths. I expect to see a stronge negative correlation between suicide rate and happiness score where low suicide rate is related to high happiness score.   

### 1) Join

```{R}
library(tidyverse)
library(readr)
MH_12 <- read_csv("MH_12.csv")
X2015 <- read_csv("2015.csv")
glimpse(MH_12)
glimpse(X2015)
mine<-inner_join(MH_12, X2015, by="Country")
glimpse(mine)
```

I joined the dataset "MH_12" (Global Suicide Data) and "X2015" (World Happiness Report) using an inner_join because I wanted to analyze only the countries that had both the suicide data and the happiness data. Since I am interested in examining how suicide rates and happiness scores are related to each other, it is logical to use countries that have both data. Also, using an inner_join does not create NAs, which makes it easier to analyze. By joining, the number of observations in "MH_12" decreased from 549 to 405. However, the number of observations in "X2015" increased from 158 to 405 since "MH_12" had rows with repeated countries. There could be a potential problem from performing inner_join since some countries would be excluded from the study, and the analysis might not represent the true "global" trend.  

### 2) Tidying

```{R}
data<-mine%>%pivot_longer(c("2015","2010","2005","2000"), names_to ="year", values_to ="suiciderate")
glimpse(data)
```

I made the joined data tidy by using pivot_longer(). Thus, the variables "2015", "2010", "2005", and "2000" were combined as one under the name "year". The values were assigned to the column "suiciderate". This increased the number of observations from 405 to 1620, and decreased the number of variables from 17 to 15.

### 3) Wrangling

```{R}
data%>%filter(year==2015)%>%select(Country, Sex, "Happiness Score", suiciderate)%>%mutate(rate=row_number(suiciderate))
data%>%filter(year==2015)%>%group_by(Sex)%>%summarize(meansuicide=mean(suiciderate))%>%arrange(desc(meansuicide))
data%>%group_by(Country,Sex)%>%summarize(sdsuicide=sd(suiciderate))
data%>%select(-Sex, -Region, -"Happiness Rank", -"Standard Error", -year, -suiciderate)%>%
  distinct()%>%rename(happyscore="Happiness Score", Economy="Economy (GDP per Capita)", Health="Health (Life Expectancy)", Trust="Trust (Government Corruption)", Dystopia="Dystopia Residual")%>%
  summarize(var(Family), min(Economy), max(Health), n_distinct(Trust), IQR(happyscore), median(Family), first(Family))
data%>%rename(happyscore="Happiness Score")%>%
  select(happyscore, suiciderate)%>%cor()
```

Here, I used all six dplyr functions filter(), select(), mutate(), group_by(), summarize(), and arrange(). Also, ten summary statistics were made using mean(), sd(), var(), min(), max(), n_distinct(), IQR(), median(), first(), and cor(). 
The first code filtered data from 2015, selected only the important columns (country, sex, happiness score, suicide rate), and created another column named "rate" to show the ranks of suicide rates from lowest to highest. The second code also filtered for year 2015, grouped by sex, summarized to find the mean of suicide rates, and arranged them in order from greatest mean suicide rate to lowest mean suicide rate. The third code grouped by two categorical variables (country, sex) and summarized to find standard deviation of suicide rates. The fourth code focused on summary statistics of various factors contributing to happiness score. The last code showed the correlation between happiness score and suicide rate, which came out to be around -10%.

### 4) Visualizing

##### Scatter Plot

```{R}
data%>%rename(Happiness_Score="Happiness Score")%>%ggplot(aes(suiciderate,Happiness_Score))+
  geom_point(aes(color=Region), size=1, alpha=.8)+
  ggtitle("Suicide Rate vs. Happiness Score")+ylab("Happiness Score")+xlab("Suicide Rate")+
  scale_x_continuous(breaks = seq(0, 80, by = 5))+
  scale_y_continuous(breaks = seq(2, 8, by = .5))+
  theme_minimal()+scale_color_brewer(palette="Paired")
```

This is a scatterplot of suicide rate and happiness score with each region in different color. There is no apparent correlation between suicide rate and happiness score since most points run vertically. However, it seems like Western Europe countries and Latin America/Caribbean countries are clustered at the top with higher happiness score, while Sub-Saharan African countries are clustered at the bottom with lower happiness score. Central and Eastern European countries seem to have high suicide rates even though their happiness score is slightly above average. Latin America/Caribbean, Eastern Asia, and Southern Asia also have few countries with high suicide rates. However, it is interesting to note that these regions with high suicide rates have varying happiness scores.

##### Bar Plot

```{R}
data%>%
  ggplot(aes(Region,suiciderate, fill=Sex))+geom_bar(stat="summary", fun.y="mean", position="dodge")+
  coord_flip()+
  ggtitle("Suicide Rate vs. Region")+xlab("Region")+ylab("Average Suicide Rate")+theme_classic()+ scale_fill_brewer(palette="Set3")
```

This is a bar plot of average suicide rates in differenct regions divided up by sex. This shows that males have higher average suicide rates compared to females in all regions. Region with lowest average suicide rates is Middle East and Northern Africa, and region with the highest average suicide rates is Eastern Asia. Regions like Central and Eastern Europe show big difference in average suicide rates between sex where males have much higher average suicide rates compared to females. Other regions like Middle East to Northern Africa does not show as much difference in sex. 

### 5) PCA

```{R}
data1<-data%>%select(-"Happiness Rank",-"Happiness Score", -"Standard Error", -year, -suiciderate, -Sex, -"Dystopia Residual")%>%distinct()
data_nums<-data1%>%select_if(is.numeric)%>%scale
rownames(data_nums)<-data1$Country
data_pca<-princomp(data_nums)
names(data_pca)
summary(data_pca, loadings=T)
eigval<-data_pca$sdev^2
round(cumsum(eigval)/sum(eigval),2) 
eigval
```

In order to do a principal component analysis, I first prepared the data by dropping irrelevant variables and scaling the numeric data. Then, I used the princomp function to calculate the principal components. The data shows that 49% of the variance is explained by principal component 1 (PC1) and 21% of the variance is explained by principal component 2 (PC2). Also, the loadings show a general strength where higher score on PC1 means lower values in individual components of happiness score. Also, higher score on PC2 means higher generosity, freedom, and trust scores, but lower economy, family, and health scores. Although PC1 and PC2 only accounts for only 70% of variance cumulatively, I decided to keep only these two since they are the ones with eigenvalues greater than 1 (Kaiser's rule).

#### Visualization

```{R}
datadf<-data.frame(PC1=data_pca$scores[,1], PC2=data_pca$scores[,2],Region=data$Region)
ggplot(datadf,aes(PC1, PC2, color=Region))+geom_point()+scale_color_brewer(palette="Paired")

data_pca$loadings[1:6,1:2]%>%as.data.frame%>%rownames_to_column%>%
  ggplot()+geom_hline(aes(yintercept=0),lty=2)+
  geom_vline(aes(xintercept=0),lty=2)+ylab("PC2")+xlab("PC1")+
  geom_segment(aes(x=0,y=0,xend=Comp.1,yend=Comp.2),arrow=arrow(),col="red")+
  geom_label(aes(x=Comp.1*0.85,y=Comp.2*1.0,label=rowname))
```

The scatterplot of PC1 against PC2 color coded by region shows that more variance is explained by PC1 compared to PC2. However, there is no cluster of points based on region, which shows that there isn't much correlation between regions and principal components. The plot of loadings on the bottom shows the vector of each variable. This shows that  Family, Health, and Economy are higly correlated (small angles between them). Also, Freedom and Trust is highly correlated. This means that countries that have more freedom have higher trust in their government. Also countries with good ecomony also have high life expectancies and happier families. Another interesting point is that countries with good economy, health, and family have lower freedom, trust and generosity. 
